### ISSUE TITLE
 Skipping a non-existent type hudson.plugins.active_directory.ActiveDirectorySecurityRealm

### ISSUE THREAD

**Issue by mrot** [hudson3-plugins/active-directory-plugin#1]
After setting the active directory as Security realm, and after an hudson restart you will get an error. Here it si the log:
2013-01-29 12:33:24.751:INFO:oejs.Server:jetty-8.1.7.v20120910
2013-01-29 12:33:26.062:INFO:oejw.StandardDescriptorProcessor:NO JSP Support for /hudson, did not find org.apache.jasper.servlet.JspServlet
2013-01-29 12:33:26.127:INFO:oejsh.ContextHandler:started o.e.j.w.WebAppContext{/hudson,file:/home/hudson/war/webapp/},file:/usr/share/hudson/hudson.war
2013-01-29 12:33:26.127:INFO:oejsh.ContextHandler:started o.e.j.w.WebAppContext{/hudson,file:/home/hudson/war/webapp/},file:/usr/share/hudson/hudson.war
Jan 29, 2013 12:33:26 PM org.eclipse.hudson.HudsonServletContextListener contextInitialized
INFO: Home directory: /home/hudson
Jan 29, 2013 12:33:26 PM hudson.util.RobustReflectionConverter doUnmarshal
WARNING: Skipping a non-existent type hudson.plugins.active_directory.ActiveDirectorySecurityRealm
Jan 29, 2013 12:33:26 PM org.eclipse.hudson.security.HudsonSecurityManager load
SEVERE: Failed to load /home/hudson/hudson-security.xml
hudson.util.IOException2: Unable to read /home/hudson/hudson-security.xml
        at hudson.XmlFile.unmarshal(XmlFile.java:140)
        at org.eclipse.hudson.security.HudsonSecurityManager.load(HudsonSecurityManager.java:366)
        at org.eclipse.hudson.security.HudsonSecurityManager.<init>(HudsonSecurityManager.java:143)
        at org.eclipse.hudson.HudsonServletContextListener.contextInitialized(HudsonServletContextListener.java:206)
        at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:771)
        at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:411)
        at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:763)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:247)
        at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1238)
        at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:706)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:480)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
        at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:95)
        at org.eclipse.jetty.server.Server.doStart(Server.java:277)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64)
        at org.eclipse.hudson.jetty.JettyLauncher.start(JettyLauncher.java:152)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.eclipse.hudson.war.Executable.launchJetty(Executable.java:134)
        at org.eclipse.hudson.war.Executable.main(Executable.java:72)
Caused by: com.thoughtworks.xstream.converters.ConversionException: null : null
---- Debugging information ----
cause-exception     : java.lang.NullPointerException
cause-message       : null
class               : org.eclipse.hudson.security.HudsonSecurityManager
required-type       : org.eclipse.hudson.security.HudsonSecurityManager
converter-type      : hudson.util.RobustReflectionConverter
path                : /hudsonSecurityManager
line number         : 43
## version             : null

```
    at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:79)
    at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
    at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:134)
    at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
    at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1034)
    at hudson.util.XStream2.unmarshal(XStream2.java:76)
    at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1018)
    at hudson.XmlFile.unmarshal(XmlFile.java:136)
    ... 21 more
```

Caused by: java.lang.NullPointerException
        at hudson.diagnosis.OldDataMonitor.report(OldDataMonitor.java:185)
        at hudson.util.RobustReflectionConverter.doUnmarshal(RobustReflectionConverter.java:264)
        at hudson.util.RobustReflectionConverter.unmarshal(RobustReflectionConverter.java:173)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
        ... 30 more

**Comment by christ66** [comment]
hudson.util.IOException2: Unable to read /home/hudson/hudson-security.xml is the issue. Are you able to create any kind of security (Test with use hudson database and Anyone can do anything security), or does it throw this exception?

**Comment by mrot** [comment]
I can create security, and I see the file beeing updated.
I can also create AD security without problems, and it works great until you restart hudson server.

In a startup made without AD security activated, I get no exceptions or warings.

I can see that in the security file made with AD plugin there is this line:
hudson-security.xml:  <securityRealm class="hudson.plugins.active_directory.ActiveDirectorySecurityRealm">

Perhaps "unable to read" means "unable to parse"?

**Comment by christ66** [comment]
Would it be possible to obtain a copy of the hudson-security.xml file you have to debug further?

**Comment by mrot** [comment]
hudson-security.xml  where I use anonymous
<?xml version='1.0' encoding='UTF-8'?>
<hudsonSecurityManager>
  <securityRealm class="hudson.security.SecurityRealm$None"/>
  <authorizationStrategy class="hudson.security.GlobalMatrixAuthorizationStrategy">
    <permission>hudson.model.Computer.Configure:hudsonadmin</permission>
    <permission>hudson.model.Computer.Delete:hudsonadmin</permission>
    <permission>hudson.model.Hudson.Administer:anonymous</permission>
    <permission>hudson.model.Hudson.Administer:hudsonadmin</permission>
    <permission>hudson.model.Hudson.Administer:hudsonwrite</permission>
    <permission>hudson.model.Hudson.Read:anonymous</permission>
    <permission>hudson.model.Hudson.Read:hudsonadmin</permission>
    <permission>hudson.model.Hudson.Read:hudsonwrite</permission>
    <permission>hudson.model.Item.Build:anonymous</permission>
    <permission>hudson.model.Item.Build:hudsonadmin</permission>
    <permission>hudson.model.Item.Build:hudsonwrite</permission>
    <permission>hudson.model.Item.Configure:anonymous</permission>
    <permission>hudson.model.Item.Configure:hudsonadmin</permission>
    <permission>hudson.model.Item.Configure:hudsonwrite</permission>
    <permission>hudson.model.Item.Create:hudsonadmin</permission>
    <permission>hudson.model.Item.Delete:anonymous</permission>
    <permission>hudson.model.Item.Delete:hudsonadmin</permission>
    <permission>hudson.model.Item.Delete:hudsonwrite</permission>
    <permission>hudson.model.Item.Read:anonymous</permission>
    <permission>hudson.model.Item.Read:hudsonadmin</permission>
    <permission>hudson.model.Item.Read:hudsonread</permission>
    <permission>hudson.model.Item.Read:hudsonwrite</permission>
    <permission>hudson.model.Item.Workspace:anonymous</permission>
    <permission>hudson.model.Item.Workspace:hudsonadmin</permission>
    <permission>hudson.model.Item.Workspace:hudsonwrite</permission>
    <permission>hudson.model.Run.Delete:anonymous</permission>
    <permission>hudson.model.Run.Delete:hudsonadmin</permission>
    <permission>hudson.model.Run.Delete:hudsonwrite</permission>
    <permission>hudson.model.Run.Update:anonymous</permission>
    <permission>hudson.model.Run.Update:hudsonadmin</permission>
    <permission>hudson.model.Run.Update:hudsonwrite</permission>
    <permission>hudson.model.View.Configure:anonymous</permission>
    <permission>hudson.model.View.Configure:hudsonadmin</permission>
    <permission>hudson.model.View.Configure:hudsonwrite</permission>
    <permission>hudson.model.View.Create:anonymous</permission>
    <permission>hudson.model.View.Create:hudsonadmin</permission>
    <permission>hudson.model.View.Create:hudsonwrite</permission>
    <permission>hudson.model.View.Delete:anonymous</permission>
    <permission>hudson.model.View.Delete:hudsonadmin</permission>
    <permission>hudson.model.View.Delete:hudsonwrite</permission>
    <permission>hudson.scm.SCM.Tag:anonymous</permission>
    <permission>hudson.scm.SCM.Tag:hudsonadmin</permission>
    <permission>hudson.scm.SCM.Tag:hudsonwrite</permission>
  </authorizationStrategy>
  <useSecurity>true</useSecurity>
  <markupFormatter class="hudson.markup.RawHtmlMarkupFormatter"/>
</hudsonSecurityManager>

then I make the one with AD groups:
hudson-security.xml
<?xml version='1.0' encoding='UTF-8'?>
<hudsonSecurityManager>
  <securityRealm class="hudson.plugins.active_directory.ActiveDirectorySecurityRealm">
    <domain>intranet.previmedical.it</domain>
    <bindPassword>Ke53Tiqvj6yMxpaKpVijOw==</bindPassword>
  </securityRealm>
  <authorizationStrategy class="hudson.security.GlobalMatrixAuthorizationStrategy">
    <permission>hudson.model.Computer.Configure:hudsonadmin</permission>
    <permission>hudson.model.Computer.Delete:hudsonadmin</permission>
    <permission>hudson.model.Hudson.Administer:anonymous</permission>
    <permission>hudson.model.Hudson.Administer:hudsonadmin</permission>
    <permission>hudson.model.Hudson.Administer:hudsonwrite</permission>
    <permission>hudson.model.Hudson.Read:anonymous</permission>
    <permission>hudson.model.Hudson.Read:hudsonadmin</permission>
    <permission>hudson.model.Hudson.Read:hudsonwrite</permission>
    <permission>hudson.model.Item.Build:hudsonadmin</permission>
    <permission>hudson.model.Item.Build:hudsonwrite</permission>
    <permission>hudson.model.Item.Configure:hudsonadmin</permission>
    <permission>hudson.model.Item.Configure:hudsonwrite</permission>
    <permission>hudson.model.Item.Create:hudsonadmin</permission>
    <permission>hudson.model.Item.Delete:hudsonadmin</permission>
    <permission>hudson.model.Item.Delete:hudsonwrite</permission>
    <permission>hudson.model.Item.Read:hudsonadmin</permission>
    <permission>hudson.model.Item.Read:hudsonread</permission>
    <permission>hudson.model.Item.Read:hudsonwrite</permission>
    <permission>hudson.model.Item.Workspace:hudsonadmin</permission>
    <permission>hudson.model.Item.Workspace:hudsonwrite</permission>
    <permission>hudson.model.Run.Delete:hudsonadmin</permission>
    <permission>hudson.model.Run.Delete:hudsonwrite</permission>
    <permission>hudson.model.Run.Update:hudsonadmin</permission>
    <permission>hudson.model.Run.Update:hudsonwrite</permission>
    <permission>hudson.model.View.Configure:hudsonadmin</permission>
    <permission>hudson.model.View.Configure:hudsonwrite</permission>
    <permission>hudson.model.View.Create:hudsonadmin</permission>
    <permission>hudson.model.View.Create:hudsonwrite</permission>
    <permission>hudson.model.View.Delete:hudsonadmin</permission>
    <permission>hudson.model.View.Delete:hudsonwrite</permission>
    <permission>hudson.scm.SCM.Tag:hudsonadmin</permission>
    <permission>hudson.scm.SCM.Tag:hudsonwrite</permission>
  </authorizationStrategy>
  <useSecurity>true</useSecurity>
  <markupFormatter class="hudson.markup.RawHtmlMarkupFormatter"/>
</hudsonSecurityManager>
